version: '3'
services:
  webserver:
    build:
      context: ./apache2
      dockerfile: Dockerfile
    container_name: apache2
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache2/fotodb.conf:/etc/apache2/sites-enabled/fotodb.conf
      - ../website:/var/www/html/fotodb
    networks:
      frontend:
      backend:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../website:/var/www/html/fotodb
    networks:
      backend:
    depends_on:
      - webserver
networks:
  frontend:
  backend: