version: '3'
services:
  php:
    image: 'php:7.3-apache-ssl'
    ports:
      - "80:80"
      - "443:443"
    environment:
      XDEBUG_CONFIG: remote_host=ERITHACUS
    volumes:
    - ../website:/var/www/html/fotodb # do not mount complete project folder into /var/www/html/fotodb
    - ~/Websites/libraries/dojo:/var/www/html/fotodb/library/dojo
    - ~/Websites/speich.net:/var/www/html/speich.net
    - /media/simon/IMAGES/Bilder:/media/sf_Bilder